#pragma once

typedef int IdxType;

enum MATRIX_UNRARY_OPERATIONS
{
	UNARY_BASE = 0,
	UNARY_TRANSPOSE = 1,
	UNARY_MINUS = 2,
	UNARY_SQUARED = 3,
	UNARY_MASKED = 4
};

enum MATRIX_BINARY_OPERATIONS
{
	BINARY_BASE = 0,
	BINARY_ADD = 1,
	BINARY_SUB = 2,
	BINARY_MATMUL = 3,
	BINARY_MATDIV = 4,
	BINARY_EMUL = 5,
	BINARY_EDIV = 6
};

enum MATRIX_MASK_UNARY_OPERATIONS
{
	MASK_UNARY_BASE = 0,
	MASK_UNARY_TRANSPOSE = 1,
	MASK_UNARY_NOT = 2
};

enum MATRIX_MASK_BINARY_OPERATIONS
{
	MASK_BINARY_BASE = 0,
	MASK_BINARY_AND = 1,
	MASK_BINARY_OR = 2,
	MASK_BINARY_NAND = 3,
	MASK_BINARY_XOR = 4,
	MASK_BINARY_EXCLUDE = 5,
};